version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: test-ping-nginx
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      - Infra-Net
    depends_on:
      - php

  php:
    image: php:8.2-fpm
    container_name: test-ping-php
    volumes:
      - ./app:/usr/share/nginx/html
    networks:
      - Infra-Net

networks:
  Infra-Net:
    external: true
